/* QUADLUD — Soleil/Lune pattern prototype
 * Copyright © 2026 Serge Benoliel. All rights reserved.
 * Product baseline: 12bb8e71d1eaa406f176d99403f34305b596e233
 * Research checkpoint: 09b714b7522b0f94faac8d7c1db786b26c61629d
 */
(()=>{'use strict';
const E=-1,M=0,S=1,SAME=0,OPP=1;
const CATALOG=[
['TANGO-P001','Écho d’égalité','Une relation = propage un symbole connu.',1],
['TANGO-P002','Bascule d’opposition','Une relation × propage le symbole opposé.',1],
['TANGO-P003','Double verrou','Deux symboles identiques consécutifs repoussent le troisième.',1],
['TANGO-P004','Sandwich','Deux symboles identiques séparés forcent l’opposé au centre.',1],
['TANGO-P005','Quota plein','Trois symboles identiques remplissent le quota de la ligne.',1],
['TANGO-P006','Paire égale repoussée','Une paire = voisine d’un symbole connu prend l’opposé.',2],
['TANGO-P007','Double au bord','Un double au bord contraint l’autre extrémité.',3],
['TANGO-P008','Bords jumeaux','Deux bords identiques repoussent leurs voisins intérieurs.',3],
['TANGO-P009','Miroir avant-bord','Un même symbole au bord et en avant-bord force l’opposé.',3],
['TANGO-P010','Bascule centrale','Une paire centrale = et un bord déterminent l’autre bord.',3],
['TANGO-P011','Paire de bord inversée','Une paire = au bord s’oriente grâce au bord opposé.',3],
['TANGO-P012','Paire × réservée','Une paire × réserve un Soleil et une Lune dans le quota.',2],
['TANGO-P013','Paire = saturée','Une paire = se place à l’opposé d’un symbole déjà doublé.',2],
['TANGO-P014','Chaîne de parité','Un symbole ancré se propage le long d’une chaîne =/×.',2],
['TANGO-P015','Écho inversé','Une égalité sur une ligne impose des oppositions complémentaires.',2],
['TANGO-P016','Double opposition','Deux paires × réservent 2 Soleils et 2 Lunes.',2],
['TANGO-P017','Chaîne relationnelle','La parité des × d’une chaîne donne la relation des extrémités.',2],
['TANGO-P018','Duo final','Deux cases finales d’une ligne équilibrée sont opposées.',2]];
const INFO=Object.fromEntries(CATALOG.map(x=>[x[0],{name:x[1],desc:x[2],tier:x[3]}]));
const LEGAL=[];for(let mask=0;mask<64;mask++){let a=Array.from({length:6},(_,i)=>(mask>>i)&1);if(a.reduce((x,y)=>x+y,0)!==3)continue;let ok=true;for(let i=0;i<4;i++)if(a[i]===a[i+1]&&a[i]===a[i+2])ok=false;if(ok)LEGAL.push(a)}
const SCENARIOS=[
{name:'A · Égalité immédiate',tier:1,state:[[S,E,E,E,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E]],edges:[[0,0,'r','=']]},
{name:'B · Quota et relations',tier:2,state:[[S,E,M,E,E,S],[E,E,E,E,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E]],edges:[[0,1,'r','×']]},
{name:'C · Bords jumeaux',tier:3,state:[[S,E,E,E,E,S],[E,E,E,E,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E]],edges:[]},
{name:'D · Duo final',tier:2,state:[[S,M,S,M,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E],[E,E,E,E,E,E]],edges:[]}];
let state,edges,givens,derived=[],match=null,undo=[],redo=[],proof=false;
const clone=x=>JSON.parse(JSON.stringify(x)),key=c=>c.join(','),same=(a,b)=>a[0]===b[0]&&a[1]===b[1],coord=c=>'ABCDEF'[c[1]]+(c[0]+1),sym=v=>v===S?'Soleil':v===M?'Lune':'vide';
function cells(f,i){return Array.from({length:6},(_,k)=>f==='row'?[i,k]:[k,i])}
function pairKey(a,b){return [key(a),key(b)].sort().join('|')}
function relationMap(){let m=new Map;for(const [r,c,d,x] of edges){let a=[r,c],b=d==='r'?[r,c+1]:[r+1,c];m.set(pairKey(a,b),x==='='?SAME:OPP)}for(const x of derived)m.set(pairKey(x.a,x.b),x.parity);return m}
function graph(){let g=new Map;for(const [pk,p] of relationMap()){let [ka,kb]=pk.split('|'),a=ka.split(',').map(Number),b=kb.split(',').map(Number);if(!g.has(ka))g.set(ka,[]);if(!g.has(kb))g.set(kb,[]);g.get(ka).push([b,p]);g.get(kb).push([a,p])}return g}
function path(a,b){let g=graph(),q=[[a,0,[]]],seen=new Set([key(a)]);for(let i=0;i<q.length;i++){let [u,p,ps]=q[i];if(same(u,b))return{parity:p,path:ps};for(const [v,e] of g.get(key(u))||[])if(!seen.has(key(v))){seen.add(key(v));q.push([v,p^e,ps.concat([{a:u,b:v,parity:e}])])}}return null}
function rel(a,b){return path(a,b)}
function models(f,i){let cs=cells(f,i),rm=relationMap();return LEGAL.filter(a=>{for(let k=0;k<6;k++){let v=state[cs[k][0]][cs[k][1]];if(v!==E&&v!==a[k])return false}for(let x=0;x<6;x++)for(let y=x+1;y<6;y++){let p=rm.get(pairKey(cs[x],cs[y]));if(p!=null&&(a[x]^a[y])!==p)return false}return true})}
function mk(id,f,i,prem,focus,cons,why){return{id,family:f,line:i,premises:prem,context:f==='graph'?focus:cells(f,i),focus,conclusions:cons,why,validated:false}}
const vp=(c,v)=>({kind:'value',cell:c,value:v}),rp=(a,b,p)=>({kind:'relation',a,b,parity:p});
function validate(m){if(m.family==='graph'){for(const c of m.conclusions){let p=path(c.a,c.b);if(c.kind==='relation'&&(!p||p.parity!==c.parity))return false}return true}let cs=cells(m.family,m.line),ms=models(m.family,m.line);if(!ms.length)return false;for(const c of m.conclusions){if(c.kind==='value'){let i=cs.findIndex(x=>same(x,c.cell));if(i<0||!ms.every(x=>x[i]===c.value))return false}else{let i=cs.findIndex(x=>same(x,c.a)),j=cs.findIndex(x=>same(x,c.b));if(i<0||j<0||!ms.every(x=>(x[i]^x[j])===c.parity))return false}}return true}
function linePatterns(f,n,tier){let cs=cells(f,n),v=cs.map(c=>state[c[0]][c[1]]),o=[],add=x=>{if(INFO[x.id].tier<=tier&&x.conclusions.length&&validate(x)){x.validated=true;o.push(x)}};
for(let i=0;i<5;i++){let r=rel(cs[i],cs[i+1]);if(!r)continue;if(v[i]!==E&&v[i+1]===E){let id=r.parity===SAME?'TANGO-P001':'TANGO-P002';add(mk(id,f,n,[vp(cs[i],v[i]),rp(cs[i],cs[i+1],r.parity)],[cs[i],cs[i+1]],[{kind:'value',cell:cs[i+1],value:v[i]^r.parity}],INFO[id].desc))}if(v[i+1]!==E&&v[i]===E){let id=r.parity===SAME?'TANGO-P001':'TANGO-P002';add(mk(id,f,n,[vp(cs[i+1],v[i+1]),rp(cs[i],cs[i+1],r.parity)],[cs[i],cs[i+1]],[{kind:'value',cell:cs[i],value:v[i+1]^r.parity}],INFO[id].desc))}}
for(let i=0;i<5;i++)if(v[i]!==E&&v[i]===v[i+1]){let c=[];if(i&&v[i-1]===E)c.push({kind:'value',cell:cs[i-1],value:1-v[i]});if(i<4&&v[i+2]===E)c.push({kind:'value',cell:cs[i+2],value:1-v[i]});add(mk('TANGO-P003',f,n,[vp(cs[i],v[i]),vp(cs[i+1],v[i])],[cs[i],cs[i+1]],c,INFO['TANGO-P003'].desc))}
for(let i=0;i<4;i++)if(v[i]!==E&&v[i]===v[i+2]&&v[i+1]===E)add(mk('TANGO-P004',f,n,[vp(cs[i],v[i]),vp(cs[i+2],v[i])],[cs[i],cs[i+2]],[{kind:'value',cell:cs[i+1],value:1-v[i]}],INFO['TANGO-P004'].desc));
for(const a of [M,S])if(v.filter(x=>x===a).length===3)add(mk('TANGO-P005',f,n,cs.filter((_,i)=>v[i]===a).map(c=>vp(c,a)),cs.filter((_,i)=>v[i]===a),cs.filter((_,i)=>v[i]===E).map(c=>({kind:'value',cell:c,value:1-a})),INFO['TANGO-P005'].desc));
if(v[0]!==E&&v[0]===v[5]){let c=[];if(v[1]===E)c.push({kind:'value',cell:cs[1],value:1-v[0]});if(v[4]===E)c.push({kind:'value',cell:cs[4],value:1-v[0]});add(mk('TANGO-P008',f,n,[vp(cs[0],v[0]),vp(cs[5],v[5])],[cs[0],cs[5]],c,INFO['TANGO-P008'].desc))}
if(v[0]!==E&&v[0]===v[4]&&v[5]===E)add(mk('TANGO-P009',f,n,[vp(cs[0],v[0]),vp(cs[4],v[4])],[cs[0],cs[4]],[{kind:'value',cell:cs[5],value:1-v[0]}],INFO['TANGO-P009'].desc));
let empty=v.map((x,i)=>x===E?i:-1).filter(i=>i>=0);if(empty.length===2&&v.filter(x=>x===M).length===2&&v.filter(x=>x===S).length===2)add(mk('TANGO-P018',f,n,cs.filter((_,i)=>v[i]!==E).map(c=>vp(c,state[c[0]][c[1]])),cs.filter((_,i)=>v[i]!==E),[{kind:'relation',a:cs[empty[0]],b:cs[empty[1]],parity:OPP}],INFO['TANGO-P018'].desc));
/* Generic classification for the remaining validated line macros: exact line support is used only to validate a recognized visible relation structure, never to invent an unlabelled move. */
let rm=relationMap(),samePairs=[],oppPairs=[];for(let i=0;i<6;i++)for(let j=i+1;j<6;j++){let p=rm.get(pairKey(cs[i],cs[j]));if(p===SAME)samePairs.push([i,j]);if(p===OPP)oppPairs.push([i,j])}
for(const [i,j] of samePairs){if(Math.abs(i-j)===1){for(let k=0;k<6;k++)if(v[k]!==E&&k!==i&&k!==j){let cons=[];for(const q of [i,j])if(v[q]===E)cons.push({kind:'value',cell:cs[q],value:1-v[k]});add(mk('TANGO-P006',f,n,[rp(cs[i],cs[j],SAME),vp(cs[k],v[k])],[cs[i],cs[j],cs[k]],cons,INFO['TANGO-P006'].desc))}}}
if(v[0]!==E&&v[1]===v[0]&&v[5]===E)add(mk('TANGO-P007',f,n,[vp(cs[0],v[0]),vp(cs[1],v[1])],[cs[0],cs[1]],[{kind:'value',cell:cs[5],value:1-v[0]}],INFO['TANGO-P007'].desc));
let mid=rm.get(pairKey(cs[2],cs[3]));if(mid===SAME&&v[0]!==E&&v[5]===E)add(mk('TANGO-P010',f,n,[vp(cs[0],v[0]),rp(cs[2],cs[3],SAME)],[cs[0],cs[2],cs[3]],[{kind:'value',cell:cs[5],value:1-v[0]}],INFO['TANGO-P010'].desc));
let edge=rm.get(pairKey(cs[0],cs[1]));if(edge===SAME&&v[5]!==E&&v[0]===E&&v[1]===E)add(mk('TANGO-P011',f,n,[rp(cs[0],cs[1],SAME),vp(cs[5],v[5])],[cs[0],cs[1],cs[5]],[{kind:'value',cell:cs[0],value:1-v[5]},{kind:'value',cell:cs[1],value:1-v[5]}],INFO['TANGO-P011'].desc));
for(const [i,j] of oppPairs){let outside=[0,1,2,3,4,5].filter(q=>q!==i&&q!==j);for(const a of [M,S])if(outside.filter(q=>v[q]===a).length>=2){let c=outside.filter(q=>v[q]===E).map(q=>({kind:'value',cell:cs[q],value:1-a}));add(mk('TANGO-P012',f,n,[rp(cs[i],cs[j],OPP)], [cs[i],cs[j]],c,INFO['TANGO-P012'].desc))}}
for(const [i,j] of samePairs){let outside=[0,1,2,3,4,5].filter(q=>q!==i&&q!==j);for(const a of [M,S])if(outside.filter(q=>v[q]===a).length>=2&&v[i]===E&&v[j]===E)add(mk('TANGO-P013',f,n,[rp(cs[i],cs[j],SAME)],[cs[i],cs[j]],[{kind:'value',cell:cs[i],value:1-a},{kind:'value',cell:cs[j],value:1-a}],INFO['TANGO-P013'].desc))}
for(const [i,j] of samePairs)if(Math.abs(i-j)===1){let c=[];for(let k=(i+1)%2;k<5;k+=2)if(!rel(cs[k],cs[k+1]))c.push({kind:'relation',a:cs[k],b:cs[k+1],parity:OPP});add(mk('TANGO-P015',f,n,[rp(cs[i],cs[j],SAME)],[cs[i],cs[j]],c,INFO['TANGO-P015'].desc))}
for(let a=0;a<oppPairs.length;a++)for(let b=a+1;b<oppPairs.length;b++){let u=[...oppPairs[a],...oppPairs[b]];if(new Set(u).size===4){let r=[0,1,2,3,4,5].filter(x=>!u.includes(x));if(r.length===2&&!rel(cs[r[0]],cs[r[1]]))add(mk('TANGO-P016',f,n,[rp(cs[oppPairs[a][0]],cs[oppPairs[a][1]],OPP),rp(cs[oppPairs[b][0]],cs[oppPairs[b][1]],OPP)],u.map(x=>cs[x]),[{kind:'relation',a:cs[r[0]],b:cs[r[1]],parity:OPP}],INFO['TANGO-P016'].desc))}}
return o}
function graphPatterns(tier){if(tier<2)return[];let o=[],g=graph(),nodes=[...g.keys()].map(k=>k.split(',').map(Number)),seen=new Set;for(const start of nodes){if(seen.has(key(start)))continue;let q=[[start,0]],par=new Map([[key(start),0]]),comp=[];for(let i=0;i<q.length;i++){let[u,p]=q[i];seen.add(key(u));comp.push(u);for(const[v,e]of g.get(key(u))||[])if(!par.has(key(v))){par.set(key(v),p^e);q.push([v,p^e])}}let anchors=comp.filter(c=>state[c[0]][c[1]]!==E);if(anchors.length){let a=anchors[0],av=state[a[0]][a[1]],c=comp.filter(x=>state[x[0]][x[1]]===E).map(x=>({kind:'value',cell:x,value:av^par.get(key(x))}));if(c.length)o.push(mk('TANGO-P014','graph',-1,[vp(a,av)],comp,c,INFO['TANGO-P014'].desc))}if(comp.length>=3)for(let i=0;i<comp.length;i++)for(let j=i+1;j<comp.length;j++){let a=comp[i],b=comp[j];if(relationMap().has(pairKey(a,b)))continue;let p=path(a,b);if(p)o.push(mk('TANGO-P017','graph',-1,p.path.map(x=>rp(x.a,x.b,x.parity)),comp,[{kind:'relation',a,b,parity:p.parity}],INFO['TANGO-P017'].desc))}}return o.map(x=>(x.validated=validate(x),x)).filter(x=>x.validated)}
function findPattern(){let tier=+document.getElementById('tier').value,o=[];for(const f of ['row','column'])for(let i=0;i<6;i++)o.push(...linePatterns(f,i,tier));o.push(...graphPatterns(tier));o=o.filter(x=>INFO[x.id].tier<=tier).sort((a,b)=>INFO[a.id].tier-INFO[b.id].tier||a.id.localeCompare(b.id));return o.find(x=>x.conclusions.some(c=>c.kind==='value'?state[c.cell[0]][c.cell[1]]===E:!relationMap().has(pairKey(c.a,c.b))))||null}
function snapshot(){return{state:clone(state),derived:clone(derived)}}function restore(x){state=clone(x.state);derived=clone(x.derived);match=null;proof=false;render();renderMatch()}function push(){undo.push(snapshot());redo=[]}
function render(){let b=document.getElementById('board');b.innerHTML='<div class="coord"></div>'+[...'ABCDEF'].map(x=>`<div class="coord">${x}</div>`).join('');for(let r=0;r<6;r++){b.insertAdjacentHTML('beforeend',`<div class="coord">${r+1}</div>`);for(let c=0;c<6;c++){let el=document.createElement('button'),cc=[r,c];el.className='cell'+(givens.has(r*6+c)?' given':'');if(match?.context.some(x=>same(x,cc)))el.classList.add('context');if(match?.focus.some(x=>same(x,cc)))el.classList.add('focus');if(match?.conclusions.some(x=>x.kind==='value'&&same(x.cell,cc)))el.classList.add('conclusion');el.textContent=state[r][c]===S?'☀️':state[r][c]===M?'🌙':'';el.onclick=()=>{if(givens.has(r*6+c))return;push();state[r][c]=state[r][c]===E?S:state[r][c]===S?M:E;match=null;render();renderMatch()};b.appendChild(el)}}requestAnimationFrame(renderRelations);document.getElementById('undoBtn').disabled=!undo.length;document.getElementById('redoBtn').disabled=!redo.length}
function renderRelations(){document.querySelectorAll('.relation').forEach(x=>x.remove());let b=document.getElementById('board'),br=b.getBoundingClientRect(),els=document.querySelectorAll('.cell'),all=[];for(const[r,c,d,x]of edges)all.push({a:[r,c],b:d==='r'?[r,c+1]:[r+1,c],parity:x==='='?SAME:OPP});all.push(...derived);for(const x of all){let a=els[x.a[0]*6+x.a[1]],c=els[x.b[0]*6+x.b[1]],ra=a.getBoundingClientRect(),rb=c.getBoundingClientRect(),e=document.createElement('div');e.className='relation'+(x.sourcePattern?' derived':'');e.textContent=x.parity===SAME?'=':'×';e.style.left=((ra.left+ra.right+rb.left+rb.right)/4-br.left)+'px';e.style.top=((ra.top+ra.bottom+rb.top+rb.bottom)/4-br.top)+'px';b.appendChild(e)}}
function text(p){return p.kind==='value'?`${coord(p.cell)} = ${sym(p.value)}`:`${coord(p.a)} ${p.parity===SAME?'=':'×'} ${coord(p.b)}`}
function renderMatch(){let t=document.getElementById('patternTitle'),p=document.getElementById('patternTier'),s=document.getElementById('patternSummary'),d=document.getElementById('patternDetails');if(!match){t.textContent='Chercher un pattern visible';p.textContent='—';s.textContent='Le recognizer recherche uniquement des configurations P001–P018 dans l’état visible, puis valide exactement leur conclusion avant affichage.';d.classList.add('hidden');document.getElementById('applyBtn').disabled=document.getElementById('explainBtn').disabled=true;return}let i=INFO[match.id];t.textContent=`${match.id.replace('TANGO-','')} — ${i.name}`;p.textContent=`Niveau ${i.tier}`;s.textContent=i.desc;d.classList.remove('hidden');d.innerHTML=`<strong>Prémisses visibles :</strong> ${match.premises.map(text).join(' · ')}<br><strong>Conclusion :</strong> ${match.conclusions.map(text).join(' · ')}${proof?`<br><br><strong>Pourquoi :</strong> ${match.why}<br><strong>Validation :</strong> la conclusion est vérifiée sur toutes les complétions légales compatibles avec l’état visible concerné.`:''}`;document.getElementById('applyBtn').disabled=document.getElementById('explainBtn').disabled=false}
function load(i){let x=SCENARIOS[i];state=clone(x.state);edges=clone(x.edges);derived=[];givens=new Set;for(let r=0;r<6;r++)for(let c=0;c<6;c++)if(state[r][c]!==E)givens.add(r*6+c);undo=[];redo=[];match=null;proof=false;document.getElementById('tier').value=x.tier;render();renderMatch()}
function init(){let sc=document.getElementById('scenario');SCENARIOS.forEach((x,i)=>sc.add(new Option(x.name,i)));sc.onchange=()=>load(+sc.value);document.getElementById('tier').onchange=()=>{match=null;render();renderMatch()};document.getElementById('findBtn').onclick=()=>{match=findPattern();proof=false;render();renderMatch();document.getElementById('status').textContent=match?`${match.id.replace('TANGO-','')} reconnu et validé depuis l’état visible.`:'Aucun pattern disponible dans l’état actuel.'};document.getElementById('explainBtn').onclick=()=>{proof=!proof;renderMatch()};document.getElementById('applyBtn').onclick=()=>{if(!match)return;push();for(const c of match.conclusions)if(c.kind==='value')state[c.cell[0]][c.cell[1]]=c.value;else derived.push({a:clone(c.a),b:clone(c.b),parity:c.parity,sourcePattern:match.id});match=null;render();renderMatch()};document.getElementById('resetBtn').onclick=()=>load(+sc.value);document.getElementById('undoBtn').onclick=()=>{if(undo.length){redo.push(snapshot());restore(undo.pop())}};document.getElementById('redoBtn').onclick=()=>{if(redo.length){undo.push(snapshot());restore(redo.pop())}};document.getElementById('catalog').innerHTML=CATALOG.map(x=>`<div class="pattern-row"><div class="pid">${x[0].replace('TANGO-','')}</div><div><div class="pname">${x[1]}</div><div class="pdesc">${x[2]}</div></div><div class="ptier">N${x[3]}</div></div>`).join('');load(0);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
document.addEventListener('DOMContentLoaded',init);globalThis.QuadludProto={LEGAL,CATALOG,INFO,findPattern,validate,getState:()=>clone(state)};
})();
